// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { ThemeProvider } from "next-themes";
// import "./globals.css";

// import { Navbar } from "@/components/Navbar";
// import { Footer } from "@/components/Footer";
// import { PopupWidget }  from "@/components/PopupWidget";


// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={inter.className}>
//         <ThemeProvider attribute="class">
//           <Navbar />
//           <div>{children}</div>
//           <Footer />
//           <PopupWidget />
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { AuthProvider } from "@/context/AuthContext";  // ✅ Import Auth Context
import "./globals.css";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { PopupWidget } from "@/components/PopupWidget";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PACER Quest",
  description: "An AI-powered interactive learning game",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>  {/* ✅ Wrap the app inside Firebase Auth Provider */}
          <ThemeProvider attribute="class">
            <Navbar />
            <main>{children}</main>  {/* ✅ Used <main> instead of <div> for better semantics */}
            <Footer />
            <PopupWidget />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
